### ISSUE TITLE
about the function count( )

### ISSUE THREAD

**Issue by yingyi666** [ostafen/clover#58] opened 2022-05-23 15:26 UTC
bro, the fun `count( )` , when there is a lot of data, it takes a long time to return.
and i see the source code ,it is implemented by `findall( )` and `len( )`the return
it takes a lot time when the data is big
such as ,now i have about 40,000 pieces of data. it takes more than a second...
maybe we should change the `fun` implementation

```go
func (here *Db) SearchContent(names []string, num int, pg int) ([]*clover.Document, int) {
	var name string
	for i, v := range names {
		if i < len(names)-1 {
			name += "(.*" + regexp.QuoteMeta(v) + ".*)|"
		} else {
			name += "(.*" + regexp.QuoteMeta(v) + ".*)"
		}
	}
	
	query := here.content.Where(clover.Field("name").Like(name))

	startT := time.Now()

	docs, _ := query.Skip(num * pg).Limit(num).FindAll()
	fmt.Printf("time.Since(startT): %v\n", time.Since(startT))
	startU := time.Now()

	pgCount, _ := query.Count()
	fmt.Printf("time.Since(startU): %v\n", time.Since(startU))

	return docs, int(math.Floor(float64(pgCount/num) + 0.0/2.0))
}
```

it print this

```bash
time.Since(startT): 204.9991ms
time.Since(startU): 1.40169s
```

**Comment by ostafen** [comment] 2022-05-23 15:29
Yes, I was aware about this, and this should be definitely optimized. Do you want to provide a PR?
The `Count()` function should be added to the StorageEngine interface{} and be implemented for the two storages currently available

**Comment by ostafen** [comment] 2022-05-23 15:34
Badger caches data internally

**Comment by yingyi666** [comment] 2022-05-23 15:43
For some reason, my skip function doesn't seem to work. The code is as follows
```go
func (here *Db) SearchContent(names []string, num int, pg int) []*clover.Document {
	var name string
	for i, v := range names {
		if i < len(names)-1 {
			name += "(.*" + regexp.QuoteMeta(v) + ".*)|"
		} else {
			name += "(.*" + regexp.QuoteMeta(v) + ".*)"
		}
	}
	fmt.Println(num, pg)
	query := here.content.Where(clover.Field("name").Like(name))

	startT := time.Now()

	docs, _ := query.Skip(num * pg).Limit(num).FindAll()
	fmt.Printf("time.Since(startT): %v\n", time.Since(startT))

	return docs
}
```

**Comment by ostafen** [comment] 2022-05-23 15:48
What do you mean by "doesn't seem to work"? What is your expected output and what are you getting?

**Comment by yingyi666** [comment] 2022-05-23 15:53
> What do you mean by "doesn't seem to work"? What is your expected output and what are you getting?

I expected to skip a few doc, but it didn't.
And then the findall function returns random disorder?

**Comment by yingyi666** [comment] 2022-05-23 15:55
I see my problem. I didn't sort.

**Comment by yingyi666** [comment] 2022-05-23 15:59
But when I sort it, its query speed slows down again.

**Comment by yingyi666** [comment] 2022-05-23 16:08
Okay, I'll start looking at the source code tomorrow.
It is 50ms before sorting and 1.3s after sorting.😔

**Comment by ostafen** [comment] 2022-05-23 16:14
I found what the problem is. I'll release soon a fix for this

**Comment by yingyi666** [comment] 2022-05-23 16:16
> I found what the problem is. I'll release soon a fix for this

thanks ,bro

**Comment by ostafen** [comment] 2022-05-23 16:20
Can you post the snipped before and after sorting?

**Comment by yingyi666** [comment] 2022-05-23 16:24
But when I don't sort, skip won't achieve the effect of the next page as I thought.

**Closed** 2022-05-24 08:09 UTC
Labels: enhancement, good first issue
